### ISSUE TITLE
Can't compile to asm.js

### ISSUE THREAD

**Issue by Hywan** [Hywan/gutenberg-parser-rs#3]
Steps to follow:

```sh
$ just build-wasm
$ wasm2asm bindings/wasm/gutenberg_post_parser.wasm
[parse exception: expected more elements in list]Fatal: error in parsing input
```

Need to investigate why.

cc @fitzgen

**Comment by fitzgen** [comment]
This looks like a bug in `wasm2asm`, do you have the latest build of binaryen? Does that fix it? If not, can you file an issue in binaryen and provide the input `.wasm` file?

**Comment by Hywan** [comment]
I've the latest commit on the master. I will feel an issue on binaryen repo. Thanks!

**Comment by Hywan** [comment]
Following the discussion https://github.com/WebAssembly/binaryen/issues/1561, @alexcrichton has successfully been able to compile this project to WASM then to ASM with https://github.com/WebAssembly/binaryen/pull/1558 and https://github.com/WebAssembly/binaryen/issues/1562 applied. We must keep an eye on it!

**Comment by alexcrichton** [comment]
FWIW the way I did this was running `wasm2es6js` from the wasm-bindgen repo with the `--wasm2asm` flag. I then edited the output manually to get it workable with direct browser inclusion and it worked after that!

**Comment by Hywan** [comment]
Great, thanks! I will try as soon as possible :-). Since IE does support asm.js, I'm also interested to compile to JS.

**Comment by Hywan** [comment]
@alexcrichton I'm just curious what steps you went through. Here are mine:

 * Build wasm binary,
 * Run `wasm2es6js --wasm2asm --output parser.asm.js parser.wasm`,
 * `sed -i '' -e 's/export //' parser.asm.js`,
 * Run it in a browser, and try to call `root('<!-- wp:foo /-->');`,
 * I have the following error:
   > ReferenceError: FUNCTION_TABLE_5 is not defined
 * When looking at the asm file, function tables are named `FUNCTION_TABLE_vi`, `FUNCTION_TABLE_viiii` etc., and not `FUNCTION_TABLE_5`. If I don't misunderstand, this is generated by `wasm2asm` (just after `wasm-dis`), see https://github.com/rustwasm/wasm-bindgen/blob/151acf8eb3db8593bf303f4c11849504569e1d23/crates/cli-support/src/wasm2es6js.rs#L356-L362,
 * I have installed binaryen to revision 65ea79b, which is the `HEAD`/latest version possible.
 * Is it a bug I should report or did I miss something?

I use this branch of this repository to start the ASM stuff, https://github.com/Hywan/gutenberg-parser-rs/compare/asmjs?expand=1.

Note: If I replace `FUNCTION_TABLE_5` and `FUNCTION_TABLE_7` by their supposedly respective `FUNCTION_TABLE_vi` and `FUNCTION_TABLE_viiii` (yeah, these numberings look strange) symbols, then I no longer have an error but an integer: `1245180`. Not sure what it represents.

Any idea?

cc @fitzgen

**Comment by alexcrichton** [comment]
@Hywan oh what version of wasm2asm did you have installed locally? The version on master still isn't ready, a few more PRs need to land

**Comment by Hywan** [comment]
I tried with version 48, and the latest version on the master, which was `6e56ef1`. Now it's `91b90b7`, but the behavior remains the same.

**Comment by Hywan** [comment]
Should I open a bug on Binaryen's repository, or is it a bug on wasm-bindgen?

**Comment by alexcrichton** [comment]
@Hywan oh that probably didn't include https://github.com/WebAssembly/binaryen/pull/1558 in that case which is required to get things working

**Comment by Hywan** [comment]
Then I will wait :-).

**Comment by Hywan** [comment]
https://github.com/WebAssembly/binaryen/pull/1558 has been merged 16 hours ago, and compilation to asm.js work. Good job @alexcrichton and @kripken! Just would like to take this ping opportunity to say thank you for all your work on Rust, Emscripten, Binaryen, and WASM. It really amazes me!
