### ISSUE TITLE
Experience: Building WASM binary

### ISSUE THREAD

**Issue by dmsnell** [Hywan/gutenberg-parser-rs#7]
These are notes I took while trying to build the WASM binary inside a Docker image

## Steps

Enter a Docker image with Rust already installed
```bash
docker run --rm -it rust:latest /bin/bash
```

Clone repo
```bash
cd /opt
git clone https://github.com/Hywan/gutenberg-parser-rs.git
```

> **Uh oh**, I don't have `just` installed: click on the link to the Just repo, see instructions. Oh good, I can install it with cargo

```bash
cargo install just
cd /opt/gutenberg-parser-rs
just build-wasm
```

> **Uh oh**, that failed. My `rust:latest` image in Docker is too old and it's yelling at me about something something "nightly." I should update to nightly…

```bash
rustup update nightly
just build-wasm
```

> **Uh oh**, it says `core` is missing for `wasp-unknown-unknown`. What does that mean? Let's try to install it

```bash
crate install core
```

drat, `crate` is the wrong command

```bash
cargo install core
```

drat, `could not find "core" in registry`
rust is trying to help

```bash
rustc --explain E0463
```

huh? A [google search for the core issue](https://www.google.com/search?q=note%3A+the+%60wasm32-unknown-unknown%60+target+may+not+be+installed+can%27t+find+crate+for+core&oq=note%3A+the+%60wasm32-unknown-unknown%60+target+may+not+be+installed+can%27t+find+crate+for+core) didn't help much

let me look at the `just` file…

```bash
vim justfile
vi justfile
nano justfile
pico justfile
```

not found - of course, the Dockerimage doesn't have my editor(s) of choice

```bash
apt-get install vim
apt-get install vi
```

?? derp

```bash
apt-get update
apt-get install vim
vim justfile
```

well I see the `-unkown-unkown` part is actually hard-coded. let's look into that

I found [this blog article on setting up wasm](https://www.hellorust.com/setup/wasm-target/) and it helped. Let's follow along…

I didn't try installing `toolchain` earlier - does that do it?
```bash
rustup toolchain install nightly
rustup update
rustup target add wasm32-unknown-unknown --toolchain nightly
just build-wasm
```

> **Uh oh**, now it fails at a missing `wasm-gc` - oops I should have read further in that blog

```bash
cargo install --git https://github.com/alexcrichton/wasm-gc
just build-wasm
```

> **Uh oh**, `sh: 1: wasm-snip: not found`. back to Google

```bash
cargo install wasm-snip
just build-wasm
```

> **Uh oh**, `sh: 1: wasm-opt: not found`. am I missing some "install deps" command? trying some things before googling

```bash
cargo install wasm-opt
```

bogus! of course it couldn't be that easy - `could not find `wasm-opt` in registry` - Google, my friend…this one is going to be more difficult. the `wasm-opt` appears to be a C++ binary I'll need to install separately and have available in the `PATH`?

the [project's README](https://github.com/WebAssembly/binaryen) doesn't really help me install it unless I do so from source, I hope I don't have to install the whole C++ toolchain and do that. let's try the easy candidates

```bash
apt-get install binaryen
```

of course not. fooey - looks like I have to compile. I found [a guide](https://tutorials.technology/tutorials/11-webassembly-initial-steps-tutorial.html) and I can hear my fans spinning already - lots of download bytes oh my.

```bash
apt-get install git cmake make ninja-build
cd /opt
git clone https://github.com/WebAssembly/binaryen
cd binaryen
cmake .
make
make install
wasm-opt
```

> while compiling I viewed a couple [prebuilt](https://github.com/vvakame/Docker-rust-wasm/blob/master/Dockerfile) [rust-wasm](https://github.com/manifoldco/docker-rust-emscripten/blob/a1b4ce6471ac9163b54b39162c11e4e963e43162/Dockerfile) dockerfiles. they use emscripten but we don't seem to be doing that here.

yay! we have `wasm-opt`

```bash
cd /opt/gutenberg-parser-rs
just build-wasm
```

> **Uh oh**, `sh: 1: brotli: not found` - this is getting really old

```bash
cargo install brotli
just build-wasm
```

oy. I am at my limit

```
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Recipe `build-wasm` failed on line 32 with exit code 101
```

did this happen because I installed `brotli` via rust?

```bash
apt-get install brotli
just build-wasm
```

nope.
okay, I ran it with `RUST_BACKRACE`

```
thread 'main' panicked at 'Unknown Argument --lgwin=24', src/bin/brotli.rs:572:7
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:463
   3: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   4: brotli::main
   5: std::rt::lang_start::{{closure}}
   6: main
   7: __libc_start_main
   8: _start
error: Recipe `build-wasm` failed on line 32 with exit code 101
```

nothing I didn't already know there - let's google the panic error. nothing helpful. explore…

```bash
brotli --help | grep lgwin
```

that looks like the main help screen

```bash
brotli --help
```

yep, identical, but only a few options

```bash
man brotli
```

not found, of course, docker…

```bash
apt-get install man
man brotli
```

```
No manual entry for brotli
See 'man 7 undocumented' for help when manual pages are not available.
```

devs are so hip.

```bash
cargo uninstall brotli # worked, cool
apt-get install brotli # already installed
apt-get remove brotli # worked
apt-get install brotli # worked
brotli --help
> bash: /usr/local/cargo/bin/brotli: No such file or directory # for pete's sake
bash
brotli # ha, new shell, new rules
just build-wasm
```

everything fails. must have been another brotli

```
Usage: brotli [--force] [--quality n] [--decompress] [--input filename] [--output filename] [--repeat iters] [--verbose] [--window n] [--custom-dictionary filename]
error: Recipe `build-wasm` failed on line 32 with exit code 1
```

well heck, I don't care about or need `brotli` or even `gzip` for that matter (inspected the `justfile` again). let's rip 'em out.

```bash
vim justfile
just build-wasm
```

looks like it built!

```bash
./bindings/wasm/bin/gutenberg-post-parser --emit-json tests/fixtures/gutenberg-demo.html
```

NODE!!!
`/usr/bin/env: 'node --experimental-modules': No such file or directory`

```bash
apt-get install nodejs
./bindings/wasm/bin/gutenberg-post-parser --emit-json tests/fixtures/gutenberg-demo.html
```

fail. again.

```bash
node -v
> bash: node: command not found
```

that's a problem.
[omitting several annoying steps to get node running in this Dockerfile

> **Uh oh** so I finally got this `.wasm` file but I can't seem to do anything with it.

```js
// node --expose-wasm
Wasm // undefined
WebAssembly // defined


WebAssembly.compile( fs.readFileSync( './parser.wasm' ) ).then( module => {
  module; // opaque thing I can't inspect
} );
```

okay well I explored quite a bit more and started reading the WASM bindings and realized this is beyond 2:30am work. sorry - I wanted to get all the way today but I failed!

I'd really like to be able to load a WASM module into `node` and then call `module.parse()` somehow.

**Comment by Hywan** [comment]
Hello :-),

To compile the WASM binary, you need:

```
$ rustup install nightly
$ rustup target add --toolchain nightly wasm32-unknown-unknown
```

Then:

```
$ git clone https://github.com/Hywan/gutenberg-parser-rs
$ cd gutenberg-parser-rs
$ cd bindings/wasm
$ cargo +nightly build --target wasm32-unknown-unknown --release
$ cd ../../
$ ls target/wasm32-unknown-unknown/release/
# and you will see a `gutenberg_post_parse_wasm.wasm` file!
```

The rest of the tools are used to shrink the size of the WASM file (436Kb right now, to 100Kb, to 32Kb with Brotli). To do that, you need `wasm-gc`, `wasm-snip`, and `wasm-opt`. After that, you need `gzip` and `brotli`. Everything is run by `just build-wasm`:

```
$ cargo install just
$ cargo install wasm-gc
$ cargo install wasm-snip
$ brew install --HEAD binaryen # on macOS, I don't remember if `--HEAD` is still useful today, I'll check
$ brew install brotli
$ just build-wasm
```

And done.

Brotli binary is not the brotli crate from Rust.

About Binaryen, there is prebuilds here https://github.com/WebAssembly/binaryen/releases.

Then, WASM is a binary. And you need to talk to it with the `WebAssembly` Web API. You will find an example in `bindings/wasm/web/`. It's basically:

```js
import { Gutenberg_Post_Parser } from './gutenberg_post_parser.mjs';

class Block {
    constructor(name, attributes, children) {
        this.name = name;
        this.attributes = attributes;
        this.children = children;
    }
}

class Phrase {
    constructor(phrase) {
        this.phrase = phrase;
    }
}

document.addEventListener(
    'DOMContentLoaded',
    () => {
        const parser = new Gutenberg_Post_Parser(Block, Phrase, './gutenberg_post_parser.wasm');

        parser.root(document.getElementById('input').value).then(
            (output) => {
                document.getElementById('output').value = JSON.stringify(output, null, 2);
            }
        );
    }
);
```

I use ECMAScript Modules on the Web side, and also on the NodeJS side, which implies the `node --experimental-modules` option (the goal is to share the “boundary” library between both environment, see bellow).

There is an example in `bindings/wasm/bin/gutenberg-post-parser`. You will see an `import { Gutenberg_Post_Parser } from './gutenberg_post_parser.mjs`. The trick is that NodeJS loads WebAssembly from a buffer, because it does not have the `Fetch` API, and also use `TextEncoder` and `TextDecoder` from the `util` module, so you have to extend the `Gutenberg_Post_Parser` class like this:

```js
class Gutenberg_Post_Parser_NodeJS extends Gutenberg_Post_Parser {
    constructor(Block, Phrase, wasmURL) {
        super(Block, Phrase, wasmURL, new util.TextEncoder(), new util.TextDecoder());
    }

    instantiateWASM(url, importObject) {
        const buffer = fs.readFileSync(url);

        return this._wasm = WebAssembly.instantiate(buffer, {}).then(obj => obj.instance);
    }
}
```

This file `bindings/wasm/gutenberg_post_parser.mjs` is the *boundary* from JS to WASM and vice versa. It's a library that reads from and writes into the WASM memory, and decodes the memory to produce JS objects (resp. `Block` and `Phrase`).

I've more documentation to write. And the tests are not finished. I'm about to finish the CI scripts, so that it will be easier for everyone to install everything. That's why there is the `artifacts` branch I used https://github.com/Hywan/gutenberg-parser-rs/tree/artifacts, it's not up-to-date though, but with Travis, we can imagine pushing the WASM binaries as release attachments.
